spring:
  http:
    multipart:
       max-file-size: 1024Mb
       max-request-size: 2048Mb
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:13306/moo?characterEncoding=utf8
    username: root
    password: 8664835
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  freemarker:
    cache: false
  #配置redis数据库连接
#  redis:
#    host: 192.168.99.100
#    port: 16379
#    database: 0 #默认是索引为的0的数据库
#    pool:
#       max-idle: 20
#       min-idle: 1
#       max-active: 20
#       max-wait: 60000
server:
   port: 8443
   context-path:  /amoo
   tomcat:
     max-threads: 800
     uri-encoding: UTF-8
     basedir: \tomcat-basedir
     access-log-enable: true
   ssl:
     key-store: classpath:keystore.p12
     key-store-password: 25564Yfs
     keyAlias: tomcat
logging:
   path: \log
   file: Moo.log
   level:
      kaizone.songmaya.moo.controller.test: "off"