server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
        config:
          server:
            git:
              uri: https://github.com/yuekaizong/Qingtian/
              searchPaths: CloudConfigServer
#                 username: yuekaizong
#                 password: xxx
          label: master
#高可用的分布式配置中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
