eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:18761/eureka
server:
     port: 18763
spring:
     application:
           name: service-ya
     zipkin:
           base-url: http://localhost:9411