spring:
  http:
    multipart:
       max-file-size: 1024Mb
       max-request-size: 2048Mb
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:13306/asmartns?characterEncoding=utf8
    username: root
    password: 8664835
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
      cache: true
      check-template-location: true
      content-type: text/html
      enabled: true
      encoding: UTF-8
      prefix: classpath:/templates/
      suffix: .html
  redis:
    host: 192.168.99.100
    port: 16379
    prefix: "APP_SERVER:MAIN:"
    default_expire_time: 14400
    max_total: 500
    max_idle: 200
    min_idle: 10
    max_wait_millis: 5000
  session:
    store-type: redis
server:
   port: 8081
   tomcat:
     max-threads: 800
     uri-encoding: UTF-8
     access-log-enable: true
logging:
   path: D:\develop\code\javaweb\haier-web\Qingtian\ASmartNsNear\log
common:
  app:
    isEncode: true
    checkAuth: true
    rootDir: D:\develop\code\javaweb\test
