eureka:
    client:
        serviceUrl:
#          defaultZone: http://localhost:18761/eureka
           #部署到docker需要更改对应服务
           defaultZone: http://eureka-server:18761/eureka
server:
     port: 18762
spring:
     application:
           name: service-hi
     zipkin:
          base-url: http://localhost:9411
