eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:18761/eureka
           #部署到docker需要更改对应服务
#           defaultZone: http://eureka-server:18761/eureka
server:
     port: 18762
spring:
     application:
           name: service-hi
#     zipkin:
#          base-url: http://localhost:9411
#config:
#  samples:
#    -
#      name: "Rabbitmq Consumer"
#      description: "@Component @RabbitListener(queue=...) @RabbitHandler"
#    -
#      name: "OAuth2"
#      description: "@EnableResourceServer extends ResourceServerConfigurerAdapter override configure(HttpSecurity http), @EnableAuthorizationServer extends AuthorizationServerConfigurerAdapter implements EnvironmentAware configure(AuthorizationServerEndpoints endpoints) configure(ClientDetailsServiceConfigurer clients)"
restTemplateMock:
  mockItems:
  -
    url: "https://mvnrepository.com/artifact/commons-io/commons-io/2.4"
    status: "ok"
    body: "hello mock"