eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:18761/eureka
server:
     port: 18762
spring:
     application:
           name: service-hi
     zipkin:
          base-url: http://localhost:9411
